name: Daily Monitoring

on:
  schedule:
    - cron: '0 3 * * *'  # daily at 03:00 UTC
  workflow_dispatch: {}

jobs:
  run-monitoring:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitoring
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          BASELINE_DATASET_REPO: praneeth232/medical-insurance-cost-prediction
          LOGS_DATASET_REPO: praneeth232/medical-insurance-logs
          REPORT_DIR: monitoring_reports
        run: |
          python monitoring/monitor.py

      - name: Upload reports artifact
        uses: actions/upload-artifact@v4
        with:
          name: monitoring-reports
          path: monitoring_reports

